/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShadersRouteImport } from './routes/shaders'
import { Route as PlaygroundRouteImport } from './routes/playground'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShadersIndexRouteImport } from './routes/shaders.index'
import { Route as ShadersNameRouteImport } from './routes/shaders.$name'
import { Route as ApiPlaygroundSplatRouteImport } from './routes/api/playground/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const ShadersRoute = ShadersRouteImport.update({
  id: '/shaders',
  path: '/shaders',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundRoute = PlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShadersIndexRoute = ShadersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShadersRoute,
} as any)
const ShadersNameRoute = ShadersNameRouteImport.update({
  id: '/$name',
  path: '/$name',
  getParentRoute: () => ShadersRoute,
} as any)
const ApiPlaygroundSplatRoute = ApiPlaygroundSplatRouteImport.update({
  id: '/api/playground/$',
  path: '/api/playground/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/playground': typeof PlaygroundRoute
  '/shaders': typeof ShadersRouteWithChildren
  '/shaders/$name': typeof ShadersNameRoute
  '/shaders/': typeof ShadersIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/playground/$': typeof ApiPlaygroundSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/playground': typeof PlaygroundRoute
  '/shaders/$name': typeof ShadersNameRoute
  '/shaders': typeof ShadersIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/playground/$': typeof ApiPlaygroundSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/playground': typeof PlaygroundRoute
  '/shaders': typeof ShadersRouteWithChildren
  '/shaders/$name': typeof ShadersNameRoute
  '/shaders/': typeof ShadersIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/playground/$': typeof ApiPlaygroundSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/playground'
    | '/shaders'
    | '/shaders/$name'
    | '/shaders/'
    | '/api/auth/$'
    | '/api/playground/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/playground'
    | '/shaders/$name'
    | '/shaders'
    | '/api/auth/$'
    | '/api/playground/$'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/playground'
    | '/shaders'
    | '/shaders/$name'
    | '/shaders/'
    | '/api/auth/$'
    | '/api/playground/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  PlaygroundRoute: typeof PlaygroundRoute
  ShadersRoute: typeof ShadersRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiPlaygroundSplatRoute: typeof ApiPlaygroundSplatRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/shaders': {
      id: '/shaders'
      path: '/shaders'
      fullPath: '/shaders'
      preLoaderRoute: typeof ShadersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shaders/': {
      id: '/shaders/'
      path: '/'
      fullPath: '/shaders/'
      preLoaderRoute: typeof ShadersIndexRouteImport
      parentRoute: typeof ShadersRoute
    }
    '/shaders/$name': {
      id: '/shaders/$name'
      path: '/$name'
      fullPath: '/shaders/$name'
      preLoaderRoute: typeof ShadersNameRouteImport
      parentRoute: typeof ShadersRoute
    }
    '/api/playground/$': {
      id: '/api/playground/$'
      path: '/api/playground/$'
      fullPath: '/api/playground/$'
      preLoaderRoute: typeof ApiPlaygroundSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ShadersRouteChildren {
  ShadersNameRoute: typeof ShadersNameRoute
  ShadersIndexRoute: typeof ShadersIndexRoute
}

const ShadersRouteChildren: ShadersRouteChildren = {
  ShadersNameRoute: ShadersNameRoute,
  ShadersIndexRoute: ShadersIndexRoute,
}

const ShadersRouteWithChildren =
  ShadersRoute._addFileChildren(ShadersRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  PlaygroundRoute: PlaygroundRoute,
  ShadersRoute: ShadersRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiPlaygroundSplatRoute: ApiPlaygroundSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/solid-start'
declare module '@tanstack/solid-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
